
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: edit your title in /docs/_config.yml
description: edit your description in /docs/_config.yml
